### ISSUE TITLE
Update to 20w06a

### ISSUE THREAD

**Issue by muzikbike** [polgaria/netherHigher#3]
I've done some testing, and the mod seems to do pretty well with the latest 1.16 snapshot. The only major bug I've seen is that surface block generation completely cuts of above y=127, leaving only netherrack (obsstructing existing surface blocks) and any generated structures:

![2020-02-06_19 55 27](https://user-images.githubusercontent.com/52297970/73973928-6ffcbb00-491b-11ea-98f2-a055c3ede297.png)
![2020-02-06_19 59 16](https://user-images.githubusercontent.com/52297970/73973939-72f7ab80-491b-11ea-9e9a-5cc81aa8afa0.png)

and the odd patch of only surface blocks with no decorative features, although these might be a vanilla thing as well (often the trees that should be there have instead teleported upwards several blocks through a ceiling, other times they don't exist at all):

![2020-02-06_20 02 04](https://user-images.githubusercontent.com/52297970/73974106-aafeee80-491b-11ea-86f5-e95dc4248b3f.png)

Otherwise the mod seems pretty stable.

**Comment by geniiii** [comment]
Updated with issues fixed as of 3bda2a18bef6d31a2de4069048db973603e72d65
