### ISSUE TITLE
Backport to forge/1.12.2

### ISSUE THREAD

**Issue by muzikbike** [polgaria/netherHigher#5]
If only because I want to see how the mod interacts with cubic chunks.

See also: https://github.com/OpenCubicChunks/CubicWorldGen/issues/73

**Comment by geniiii** [comment]
This shouldn't be too hard, considering how tiny of a mod it is. ((I hope))

**Comment by muzikbike** [comment]
closing as the notice on this mod's readme has announced discontinuation for a while now - feel free to reopen in future if work starts again
